### ISSUE TITLE
Could not find or access '/srv/platform/bootstrap/tasks/custom.yml' on the Ansible Controller.

### ISSUE THREAD

**Issue by lex51** [rockstat/bootstrap#6]
Could not find or access '/srv/platform/bootstrap/tasks/custom.yml' on the Ansible Controller.

Лечится созданием пустого файла custom.yml в директории /srv/platform/bootstrap/tasks/

**Comment by madiedinro** [comment]
fixed. kickstart script touches tasks/custom.yml
